version: "3.5"

services:
  controller: &service_base
    build:
      context: .
    volumes:
      - ./:/polytank
    networks:
      - envoy-grpc-sample
    ports:
      - 33330:33330
    depends_on:
      - worker-1
      - worker-2
  worker-1: &worker
    <<: *service_base
    ports: []
    depends_on: []
  worker-2:
    <<: *worker

networks:
  envoy-grpc-sample:
    external:
      name: envoy_grpc_sample_mesh
