// Code generated by protoc-gen-go. DO NOT EDIT.
// source: worker.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DistributeRequest struct {
	Plugin               []byte   `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistributeRequest) Reset()         { *m = DistributeRequest{} }
func (m *DistributeRequest) String() string { return proto.CompactTextString(m) }
func (*DistributeRequest) ProtoMessage()    {}
func (*DistributeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{0}
}

func (m *DistributeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributeRequest.Unmarshal(m, b)
}
func (m *DistributeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributeRequest.Marshal(b, m, deterministic)
}
func (m *DistributeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributeRequest.Merge(m, src)
}
func (m *DistributeRequest) XXX_Size() int {
	return xxx_messageInfo_DistributeRequest.Size(m)
}
func (m *DistributeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DistributeRequest proto.InternalMessageInfo

func (m *DistributeRequest) GetPlugin() []byte {
	if m != nil {
		return m.Plugin
	}
	return nil
}

type ExecuteRequest struct {
	Concurrency    uint32 `protobuf:"varint,1,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	TimeoutSeconds uint32 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// Types that are valid to be assigned to Max:
	//	*ExecuteRequest_Count
	//	*ExecuteRequest_Seconds
	Max                  isExecuteRequest_Max `protobuf_oneof:"max"`
	ExMap                map[string]string    `protobuf:"bytes,5,rep,name=ex_map,json=exMap,proto3" json:"ex_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ExecuteRequest) Reset()         { *m = ExecuteRequest{} }
func (m *ExecuteRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteRequest) ProtoMessage()    {}
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{1}
}

func (m *ExecuteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteRequest.Unmarshal(m, b)
}
func (m *ExecuteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteRequest.Merge(m, src)
}
func (m *ExecuteRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteRequest.Size(m)
}
func (m *ExecuteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteRequest proto.InternalMessageInfo

func (m *ExecuteRequest) GetConcurrency() uint32 {
	if m != nil {
		return m.Concurrency
	}
	return 0
}

func (m *ExecuteRequest) GetTimeoutSeconds() uint32 {
	if m != nil {
		return m.TimeoutSeconds
	}
	return 0
}

type isExecuteRequest_Max interface {
	isExecuteRequest_Max()
}

type ExecuteRequest_Count struct {
	Count uint32 `protobuf:"varint,3,opt,name=count,proto3,oneof"`
}

type ExecuteRequest_Seconds struct {
	Seconds uint32 `protobuf:"varint,4,opt,name=seconds,proto3,oneof"`
}

func (*ExecuteRequest_Count) isExecuteRequest_Max() {}

func (*ExecuteRequest_Seconds) isExecuteRequest_Max() {}

func (m *ExecuteRequest) GetMax() isExecuteRequest_Max {
	if m != nil {
		return m.Max
	}
	return nil
}

func (m *ExecuteRequest) GetCount() uint32 {
	if x, ok := m.GetMax().(*ExecuteRequest_Count); ok {
		return x.Count
	}
	return 0
}

func (m *ExecuteRequest) GetSeconds() uint32 {
	if x, ok := m.GetMax().(*ExecuteRequest_Seconds); ok {
		return x.Seconds
	}
	return 0
}

func (m *ExecuteRequest) GetExMap() map[string]string {
	if m != nil {
		return m.ExMap
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ExecuteRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ExecuteRequest_Count)(nil),
		(*ExecuteRequest_Seconds)(nil),
	}
}

type Result struct {
	ProcessName          string   `protobuf:"bytes,1,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	IsSuccess            bool     `protobuf:"varint,2,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	StartTimestampUsec   int64    `protobuf:"varint,3,opt,name=start_timestamp_usec,json=startTimestampUsec,proto3" json:"start_timestamp_usec,omitempty"`
	ElapsedTimeUsec      int64    `protobuf:"varint,4,opt,name=elapsed_time_usec,json=elapsedTimeUsec,proto3" json:"elapsed_time_usec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{2}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetProcessName() string {
	if m != nil {
		return m.ProcessName
	}
	return ""
}

func (m *Result) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *Result) GetStartTimestampUsec() int64 {
	if m != nil {
		return m.StartTimestampUsec
	}
	return 0
}

func (m *Result) GetElapsedTimeUsec() int64 {
	if m != nil {
		return m.ElapsedTimeUsec
	}
	return 0
}

type Results struct {
	List                 []*Result `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Results) Reset()         { *m = Results{} }
func (m *Results) String() string { return proto.CompactTextString(m) }
func (*Results) ProtoMessage()    {}
func (*Results) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{3}
}

func (m *Results) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Results.Unmarshal(m, b)
}
func (m *Results) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Results.Marshal(b, m, deterministic)
}
func (m *Results) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Results.Merge(m, src)
}
func (m *Results) XXX_Size() int {
	return xxx_messageInfo_Results.Size(m)
}
func (m *Results) XXX_DiscardUnknown() {
	xxx_messageInfo_Results.DiscardUnknown(m)
}

var xxx_messageInfo_Results proto.InternalMessageInfo

func (m *Results) GetList() []*Result {
	if m != nil {
		return m.List
	}
	return nil
}

type WaitResponse struct {
	Results              []*Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	IsContinue           bool      `protobuf:"varint,2,opt,name=is_continue,json=isContinue,proto3" json:"is_continue,omitempty"`
	Current              uint32    `protobuf:"varint,3,opt,name=current,proto3" json:"current,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *WaitResponse) Reset()         { *m = WaitResponse{} }
func (m *WaitResponse) String() string { return proto.CompactTextString(m) }
func (*WaitResponse) ProtoMessage()    {}
func (*WaitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{4}
}

func (m *WaitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaitResponse.Unmarshal(m, b)
}
func (m *WaitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaitResponse.Marshal(b, m, deterministic)
}
func (m *WaitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaitResponse.Merge(m, src)
}
func (m *WaitResponse) XXX_Size() int {
	return xxx_messageInfo_WaitResponse.Size(m)
}
func (m *WaitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WaitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WaitResponse proto.InternalMessageInfo

func (m *WaitResponse) GetResults() []*Result {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *WaitResponse) GetIsContinue() bool {
	if m != nil {
		return m.IsContinue
	}
	return false
}

func (m *WaitResponse) GetCurrent() uint32 {
	if m != nil {
		return m.Current
	}
	return 0
}

func init() {
	proto.RegisterType((*DistributeRequest)(nil), "pb.DistributeRequest")
	proto.RegisterType((*ExecuteRequest)(nil), "pb.ExecuteRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb.ExecuteRequest.ExMapEntry")
	proto.RegisterType((*Result)(nil), "pb.Result")
	proto.RegisterType((*Results)(nil), "pb.Results")
	proto.RegisterType((*WaitResponse)(nil), "pb.WaitResponse")
}

func init() { proto.RegisterFile("worker.proto", fileDescriptor_e4ff6184b07e587a) }

var fileDescriptor_e4ff6184b07e587a = []byte{
	// 504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x26, 0xfd, 0xdd, 0x4e, 0xcb, 0x7e, 0x8e, 0xc6, 0x14, 0x15, 0x0d, 0x4a, 0x85, 0xc4, 0x00,
	0x29, 0x9b, 0xca, 0x8f, 0x26, 0xb8, 0x03, 0x2a, 0x71, 0x03, 0x17, 0x2e, 0x68, 0x97, 0x51, 0xea,
	0x1d, 0x2a, 0x6b, 0x49, 0x6c, 0x62, 0x1b, 0xda, 0x17, 0xe0, 0x59, 0x78, 0x34, 0x1e, 0x03, 0xd9,
	0x4e, 0xb4, 0xa2, 0xd1, 0x3b, 0x9f, 0xef, 0xc7, 0x39, 0xf9, 0xfc, 0xc1, 0xf0, 0xa7, 0xac, 0xae,
	0xa9, 0x4a, 0x54, 0x25, 0x8d, 0xc4, 0x96, 0x5a, 0x8c, 0xee, 0x2f, 0xa5, 0x5c, 0xe6, 0x74, 0xe6,
	0x91, 0x85, 0xfd, 0x76, 0x46, 0x85, 0x32, 0xeb, 0x20, 0x98, 0x3c, 0x87, 0xc3, 0x0f, 0x42, 0x9b,
	0x4a, 0x2c, 0xac, 0x21, 0x46, 0xdf, 0x2d, 0x69, 0x83, 0xc7, 0xd0, 0x53, 0xb9, 0x5d, 0x8a, 0x32,
	0x8e, 0xc6, 0xd1, 0xe9, 0x90, 0xd5, 0xd3, 0xe4, 0x57, 0x0b, 0xf6, 0x66, 0x2b, 0xe2, 0x1b, 0xd2,
	0x31, 0x0c, 0xb8, 0x2c, 0xb9, 0xad, 0x2a, 0x2a, 0xf9, 0xda, 0xeb, 0xef, 0xb2, 0x4d, 0x08, 0x9f,
	0xc0, 0xbe, 0x11, 0x05, 0x49, 0x6b, 0x52, 0x4d, 0x5c, 0x96, 0x57, 0x3a, 0x6e, 0x79, 0xd5, 0x5e,
	0x0d, 0xcf, 0x03, 0x8a, 0xc7, 0xd0, 0xe5, 0xd2, 0x96, 0x26, 0x6e, 0x3b, 0xfa, 0xe3, 0x1d, 0x16,
	0x46, 0x1c, 0x41, 0xbf, 0x31, 0x76, 0x6a, 0xa6, 0x01, 0xf0, 0x25, 0xf4, 0x68, 0x95, 0x16, 0x99,
	0x8a, 0xbb, 0xe3, 0xf6, 0xe9, 0x60, 0x7a, 0x92, 0xa8, 0x45, 0xf2, 0xef, 0x8a, 0xc9, 0x6c, 0xf5,
	0x29, 0x53, 0xb3, 0xd2, 0x54, 0x6b, 0xd6, 0x25, 0x77, 0x1e, 0x5d, 0x00, 0xdc, 0x80, 0x78, 0x00,
	0xed, 0x6b, 0x0a, 0xab, 0xef, 0x32, 0x77, 0xc4, 0x23, 0xe8, 0xfe, 0xc8, 0x72, 0x4b, 0x7e, 0xd1,
	0x5d, 0x16, 0x86, 0x37, 0xad, 0x8b, 0xe8, 0x5d, 0x17, 0xda, 0x45, 0xb6, 0x9a, 0xfc, 0x8e, 0xa0,
	0xc7, 0x48, 0xdb, 0xdc, 0xe0, 0x23, 0x18, 0xaa, 0x4a, 0x72, 0xd2, 0x3a, 0x2d, 0xb3, 0x82, 0xea,
	0x6b, 0x06, 0x35, 0xf6, 0x39, 0x2b, 0x08, 0x4f, 0x00, 0x84, 0x4e, 0xb5, 0xe5, 0x0e, 0xf1, 0x77,
	0xee, 0xb0, 0x5d, 0xa1, 0xe7, 0x01, 0xc0, 0x73, 0x38, 0xd2, 0x26, 0xab, 0x4c, 0xea, 0xf2, 0xd0,
	0x26, 0x2b, 0x54, 0x6a, 0x35, 0x71, 0x1f, 0x43, 0x9b, 0xa1, 0xe7, 0xbe, 0x34, 0xd4, 0x57, 0x4d,
	0x1c, 0x9f, 0xc1, 0x21, 0xe5, 0x99, 0xd2, 0x74, 0xe5, 0x3d, 0x41, 0xde, 0xf1, 0xf2, 0xfd, 0x9a,
	0x70, 0x06, 0xa7, 0x9d, 0x3c, 0x85, 0x7e, 0xd8, 0x54, 0xe3, 0x03, 0xe8, 0xe4, 0x42, 0x9b, 0x38,
	0xf2, 0x51, 0x81, 0x8b, 0x2a, 0x50, 0xcc, 0xe3, 0x13, 0x09, 0xc3, 0xcb, 0x4c, 0x18, 0x46, 0x5a,
	0xc9, 0x52, 0x13, 0x3e, 0x86, 0x7e, 0x15, 0xac, 0xff, 0xb1, 0x34, 0x14, 0x3e, 0x84, 0x81, 0xd0,
	0x29, 0x97, 0xa5, 0x11, 0x65, 0x1d, 0xd9, 0x0e, 0x03, 0xa1, 0xdf, 0xd7, 0x08, 0xc6, 0xd0, 0x0f,
	0x65, 0xa8, 0x5f, 0x96, 0x35, 0xe3, 0xf4, 0x4f, 0x04, 0xbd, 0x4b, 0x5f, 0x57, 0x7c, 0x0b, 0x70,
	0xd3, 0x43, 0xbc, 0xe7, 0x3e, 0x74, 0xab, 0x97, 0xa3, 0xe3, 0x24, 0x54, 0x39, 0x69, 0xaa, 0x9c,
	0xcc, 0x5c, 0x95, 0xf1, 0x15, 0xf4, 0xeb, 0x37, 0x47, 0xbc, 0x5d, 0x80, 0xad, 0xb6, 0x29, 0x74,
	0xdc, 0xff, 0xe2, 0x16, 0x7e, 0x74, 0xe0, 0xee, 0xda, 0x4c, 0xe4, 0x3c, 0xc2, 0xd7, 0xd0, 0x99,
	0x1b, 0xa9, 0xb6, 0x7a, 0xb6, 0xe0, 0x8b, 0x9e, 0x9f, 0x5f, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0x97, 0x08, 0xbf, 0x15, 0x9f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkerClient interface {
	Distribute(ctx context.Context, in *DistributeRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Wait(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Worker_WaitClient, error)
	Stop(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type workerClient struct {
	cc *grpc.ClientConn
}

func NewWorkerClient(cc *grpc.ClientConn) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) Distribute(ctx context.Context, in *DistributeRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.Worker/Distribute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.Worker/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) Wait(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Worker_WaitClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Worker_serviceDesc.Streams[0], "/pb.Worker/Wait", opts...)
	if err != nil {
		return nil, err
	}
	x := &workerWaitClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Worker_WaitClient interface {
	Recv() (*WaitResponse, error)
	grpc.ClientStream
}

type workerWaitClient struct {
	grpc.ClientStream
}

func (x *workerWaitClient) Recv() (*WaitResponse, error) {
	m := new(WaitResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *workerClient) Stop(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.Worker/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServer is the server API for Worker service.
type WorkerServer interface {
	Distribute(context.Context, *DistributeRequest) (*empty.Empty, error)
	Execute(context.Context, *ExecuteRequest) (*empty.Empty, error)
	Wait(*empty.Empty, Worker_WaitServer) error
	Stop(context.Context, *empty.Empty) (*empty.Empty, error)
}

// UnimplementedWorkerServer can be embedded to have forward compatible implementations.
type UnimplementedWorkerServer struct {
}

func (*UnimplementedWorkerServer) Distribute(ctx context.Context, req *DistributeRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Distribute not implemented")
}
func (*UnimplementedWorkerServer) Execute(ctx context.Context, req *ExecuteRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (*UnimplementedWorkerServer) Wait(req *empty.Empty, srv Worker_WaitServer) error {
	return status.Errorf(codes.Unimplemented, "method Wait not implemented")
}
func (*UnimplementedWorkerServer) Stop(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}

func RegisterWorkerServer(s *grpc.Server, srv WorkerServer) {
	s.RegisterService(&_Worker_serviceDesc, srv)
}

func _Worker_Distribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).Distribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Worker/Distribute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).Distribute(ctx, req.(*DistributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Worker/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_Wait_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServer).Wait(m, &workerWaitServer{stream})
}

type Worker_WaitServer interface {
	Send(*WaitResponse) error
	grpc.ServerStream
}

type workerWaitServer struct {
	grpc.ServerStream
}

func (x *workerWaitServer) Send(m *WaitResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Worker_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Worker/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).Stop(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Worker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Distribute",
			Handler:    _Worker_Distribute_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _Worker_Execute_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Worker_Stop_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Wait",
			Handler:       _Worker_Wait_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "worker.proto",
}
